### ISSUE TITLE
Instruction page is non-existent

### ISSUE THREAD

**Issue by jpozin** [eoncarlyle/state-economy-game#39]
At the bottom of the GDPLE site, there is a hyperlink to instructions for the game. However, the hyperlink redirects to https://gdple.iainschmitt.com/about, which shows a 404 error.

**Comment by eoncarlyle** [comment]
Dear Valued GDPLE Player,

An NGINX misconfiguration prevented this page from being accessed.

Please let us know if you are still not able to see the 'about' page, as a recent configuration change should have addressed this issue!
