### ISSUE TITLE
GDP Data is Old

### ISSUE THREAD

**Issue by jpozin** [eoncarlyle/state-economy-game#42]
The GDP data used in this game is from 2022, but it's almost 2025. As the states repeat over time, so do the GDPs, which makes the game too easy after a while. Can the GDP data used in this game be updated to a more recent year?

**Comment by eoncarlyle** [comment]
Dear valued player, this is an entirely reasonable request. As you could image the BEA has already released data for 2023 and the only reason I'm not doing this tonight is that I have no idea where my old script is for turning the CSV data into a state-denominated JSON file

https://apps.bea.gov/iTable/?reqid=70&step=1&isuri=1&acrdn=3#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI1MDUiXSxbIk1ham9yX0FyZWEiLCIwIl0sWyJTdGF0ZSIsWyIwIl1dLFsiQXJlYSIsWyJYWCJdXSxbIlN0YXRpc3RpYyIsWyItMSJdXSxbIlVuaXRfb2ZfbWVhc3VyZSIsIkxldmVscyJdLFsiWWVhciIsWyIyMDIzIl1dLFsiWWVhckJlZ2luIiwiLTEiXSxbIlllYXJfRW5kIiwiLTEiXV19

**Comment by eoncarlyle** [comment]
@jpozin I finally got around to updating the GDP data, do not hesitate to report any issues that could be related to the update!=

**Comment by jpozin** [comment]
Thank you!!
